name: CI
on:
  pull_request:
  # Trigger on merges to `main` to allow `gradle/gradle-build-action` runs to write their caches.
  # https://github.com/gradle/gradle-build-action#using-the-caches-read-only
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
#      - uses: actions/checkout@v4
#        with:
#          path: multiplatform-swiftpackage
#          repository: luca992/multiplatform-swiftpackage
#          token: ${{ secrets.TOKEN }}
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v4

#      - run: sed -i '' '/sign(/d' build.gradle.kts
#        working-directory: multiplatform-swiftpackage
#      - run: ./gradlew -PRELEASE_SIGNING_ENABLED=false -Pversion=2.3.0-SNAPSHOT -PVERSION_NAME=2.3.0-SNAPSHOT publishToMavenLocal
#        working-directory: multiplatform-swiftpackage

      - name: local.properties
        working-directory: library
        run: |
          cat <<TEXTFILE > local.properties
          datadog.clientToken.android=noop
          datadog.clientToken.ios=noop
          datadog.clientToken.js=noop
          TEXTFILE

      - run: ./gradlew assemble
      - run: ./gradlew jsBrowserDevelopmentWebpack

      - run: brew install xcodegen

      - run: ./gradlew generateXcodeProject

      - run: xcodebuild -scheme Sample build CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO
        working-directory: ios

      - run: ./gradlew check
